name: Build and Deploy Unity WebGL

on:
  push:
    branches: [dev]  # change this to your working branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL with Unity
        uses: game-ci/unity-actions@v2
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.16f1  # Replace with your Unity version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL # Match with Unity's WebGL build path
